blog/config/routes.rb
Blog::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get "sessions/new"

  resources :posts do
    resources :images
  end

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :home
  #resources :posts
  resources :sessions

  root :to => "home#index"
end

blog/app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

blog/app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

blog/app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

blog/app/models/image.rb
# image for blog
class Image < ActiveRecord::Base
  attr_accessible :url, :photo
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/


  belongs_to :imageable, polymorphic: true
end

blog/app/models/post.rb
# post for blog
class Post < ActiveRecord::Base
  attr_accessible :title, :body, :published_at
  belongs_to :user
  has_many :images, as: :imageable

  scope :published, -> { where('published_at IS NOT NULL') }
  self.per_page = 3

  def format_date
    created_at.strftime("%b %d, %y")
  end
end

blog/app/models/user.rb
# user for blog
class User < ActiveRecord::Base
  attr_accessible :birthday, :email, :first_name, :last_name, :password, :username, :password_confirmation
  attr_accessor :password

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save :encrypt_password

  has_many :posts
  has_many :images, as: :imageable

  validates :password, length: { minimum: 8 }
  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates :email, format: EMAIL_REGEX
  validates :username, presence: true
  validates :username, uniqueness: true

  scope :adult, -> { where('? - birthday >= 18', Time.now) }

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

blog/app/controllers/application_controller.rb
# to do
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authorize
    redirect_to log_in_path unless current_user
  end

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  # skip_before_filter :check_auth, only: [:index]
  # before_filter :book, only: [:show, :edit, :update, :destroy]
  # before_filter :book, skip: [:new, :create, :index]
  def index
    order = params[:order] || 'asc'
    @users = User.order("id #{order}")
  end
end

blog/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :load_imageable

  def index
    @images = @imageable.images
  end

  def new
    @image = @imageable.images.new
  end

  def create
    @image = @imageable.images.new(params[:image])
    if @image.save
      redirect_to @imageable, notice: 'Comment created.'
    else
      render :new
    end
  end

  private

  def load_imageable
    resource, id = request.path.split('/')[1, 2]
    @imageable = resource.singularize.classify.constantize.find(id)
  end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize
  before_filter :set_post, only: [:update, :edit, :destroy]

  def index
    #@posts ||= Post.order('created_at DESC')
    @posts = Post.paginate(:page => params[:page]).order('created_at DESC')
    @post = Post.new
    respond_to do |format|
      format.html
      format.js { render 'shared/post_page' }
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @imageable = @post
    @images = @imageable.images
    @image = Image.new
  end

  def create
    @post = current_user.posts.create(params[:post])
    respond_to do |format|
      format.html { render(:new) }
      format.js
    end
  end

  def update
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.js
      else
        format.html { render action: 'edit' }
        #format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @post.destroy
  end

  private
  def set_post
    @post = current_user.posts.find(params[:id])
  end

end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

blog/app/controllers/users_controller.rb
# controller
class UsersController < ApplicationController
  before_filter :authorize, except: [:new, :create]
  def index
    order = params[:order] || 'asc'
    @users = User.order("id #{order}")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, notice: 'Signed up!'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to root_url, notice: 'Successful update'
    else
      render 'edit'
    end
  end
end

blog/app/helpers/application_helper.rb
# helper
module ApplicationHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/helpers/image_helper.rb
module ImageHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/helpers/sessions_helper.rb
module SessionsHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/home/index.html.slim
.center.jumbotron
  h1
    | Ruby on Rails 2017
  h2
    |  Home work application from OKots
  = link_to "Sign up now!", sign_up_path, class: "btn btn-lg btn-primary"
.center.jumbotron
  = image_tag("learn_ruby_on_rails.jpg", alt: "Rails logo")

blog/app/views/image/_images.html.erb
<div id="comments">
<% @images.each do |image| %>
  <div class="comment">
    <%= simple_format image.url %>
  </div>
<% end %>
</div>

blog/app/views/image/index.html.erb
<h1>Comments</h1>

<div id="comments">
<% @images.each do |image| %>
  <div class="comment">
    <%= simple_format image.url %>
  </div>
<% end %>
</div>

blog/app/views/images/_form.html.erb
<%= form_for [@imageable, @image], :html => { :multipart => true }  do |f| %>
  <% if @image.errors.any? %>
    <div class="error_messages">
      <h2>Please correct the following errors.</h2>
      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :url, rows: 8 %>
  </div>
  <div class="formList">
        <%= f.label :photo, "Photo" %>
        <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/images/_images.html.erb
<div id="comments">
<% @images.each do |image| %>
  <div class="comment">
    <%= simple_format image.url %>
    <%= image_tag image.photo.url %>
  </div>
<% end %>
</div>

blog/app/views/images/index.html.erb
<h1>Comments</h1>

<%= render 'images' %>


<p><%= link_to "New image", [:new, @imageable, :image] %></p>

blog/app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Blog</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'Ckeditor.cdn_url' %>
    </head>

    <body>

        <nav class="navbar navbar-default " role="navigation">

                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <div class="navbar-brand navbar-brand-centered"><%= link_to 'Soft Group', '/' %></div>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-brand-centered">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#">Home work 8</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <% if current_user %>
                        <li>
                            <p class="navbar-text">Signed in as
                                <%= current_user.full_name %>
                            </p>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Task
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <%= link_to 'Update profile', edit_user_path(current_user.id) %>
                                </li>
                                <li>
                                    <%= link_to 'Posts', posts_path%>
                                </li>
                                <li>
                                    <a href="#">Something else here</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">Separated link</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">One more separated link</a>
                                </li>
                            </ul>
                        </li>
                        <li><%= link_to "Log out", log_out_path %></li>
                    </ul>
                <% else %>
                    <ul class="nav navbar-nav navbar-right">

                        <li><%= link_to 'Log in', log_in_path %></li>
                        <li><%= link_to 'Sign up', sign_up_path %></li>

                    </ul>
                    <% end %>

                </div>
                <!-- /.navbar-collapse -->

            <!-- /.container-fluid -->
        </nav>

        <div class="container">
            <%= yield %>
        </div>
    </body>
</html>

blog/app/views/posts/_form.html.erb
<div class="panel-body">
    <div class="col-md-12">
        <div class="icerik-bilgi">
          <%= form_for @post, remote: true do |f| %>
            <% if @post.errors.any? %>
            <div id="errorExplanation">
              <h2><%= pluralize(@post.errors.count, "error") %></h2>
              <ul>
              <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
            <% end %>

            <div class="field">
              <%= f.label :title %><br />
              <%= f.text_field :title %>
            </div>
            <div class="field">
              <%= f.label :body %><br />
              <%= f.cktext_area :body,  :class => "form-control", :rows => "5" %>
            </div>
            <div class="actions">
              <%= f.submit %>
            </div>
          <% end %>
        </div>
    </div>
</div>

blog/app/views/posts/_post.html.erb
<div class="container" id="post_<%= post.id %>">
    <div class="col-xs-12 col-sm-6 col-lg-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <!-- <img class="[ img-circle pull-left ]" src="images/person.png" alt="ok" /> -->
                <div class="row">
                    <div class="col-md-9">
                        <%= image_tag("person.png", class: "[ img-circle pull-left ]")%>
                        <h3><%= post.user.try(:full_name) %></h3>
                        <h5>
                            <span>Shared publicly</span>
                            -
                            <span><%= post.format_date %></span>
                            <%= link_to 'Show', post %> 
                        </h5>
                    </div>
                    <div class="col-md-3">
                        <% if current_user.id == post.user_id %>

                        <span style="float: right">
                            <%= link_to edit_post_path(post), remote: true do %>
                            <i class="fa fa-pencil"></i>
                            <% end %>
                            <%= link_to '✕', post_path(post), method: :delete, remote: true, class: 'delete_post' %></span>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <div class="col-md-12">
                    <div class="icerik-bilgi">
                        <h2><%= best_in_place post, :title, :as => :input, :ok_button => 'Save', :cancel_button => 'Cancel' %></h2>
                          <% if post.body.length > 50 %>
                          <%= truncate_html(post.body, length: 50) %>
                          <%= link_to_function '...Read more', "$(this).parent().html('#{escape_javascript post.body}')" %>
                          <% else %>
                            <%= post.body.html_safe %>
                          <% end %>
                        <%= social_share_button_tag(@post.title) %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

blog/app/views/posts/_row.html.erb
<div class="container" id="post_<%= post.id %>">
    <div class="col-xs-12 col-sm-6 col-lg-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <!-- <img class="[ img-circle pull-left ]" src="images/person.png" alt="ok" /> -->
                <div class="row">
                    <div class="col-md-9">
                        <%= image_tag("person.png", class: "[ img-circle pull-left ]")%>
                        <h3><%= post.user.try(:full_name) %></h3>
                        <h5>
                            <span>Shared publicly</span>
                            -
                            <span><%= post.format_date %></span>
                        </h5>
                    </div>
                    <div class="col-md-3">
                        <% if current_user.id == post.user_id %>

                        <span style="float: right">
                            <%= link_to edit_post_path(post), remote: true do %>
                            <i class="fa fa-pencil"></i>
                            <% end %>
                            <%= link_to '✕', post_path(post), method: :delete, remote: true, class: 'delete_post' %></span>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <div class="col-md-12">
                    <div class="icerik-bilgi">
                        <h2><%= post.title %></h2>
                        <% if post.body.length > 50 %>
                          <%= truncate_html(post.body, length: 50) %>
                          <%= link_to_function '...Read more', "$(this).parent().html('#{escape_javascript post.body}')" %>
                        <% else %>
                          <%= post.body.html_safe %>
                        <% end %>
                        <%= social_share_button_tag(@post.title) %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

blog/app/views/posts/create.js.erb
$('#post_holder').prepend("<%= j(render 'post', post: @post) %>");
$('form')[0].reset()
$('.collapse').collapse('toggle')

blog/app/views/posts/edit.html.erb
<h1 >Edit Post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path, class: "btn btn-primary btn-sm"  %>

blog/app/views/posts/edit.js.erb
$("#post_<%= @post.id %>").replaceWith("<%= j(render 'form', post: @post) %>");

blog/app/views/posts/index.html.erb
<h1>Listing posts</h1>
<!-- <%= link_to 'Add New Post', "#collapseExample", :class => "btn btn-primary", id: 'add_post', :role =>  "button", data: { collapse: 'toggle'}, :"aria-expanded" =>  "false", :"aria-controls" => "collapseExample" %> -->
<button class="btn btn-primary" id="add_post" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
  Add New Post
</button>
<br />
<div class="collapse" id="collapseExample">
  <div class="well">
    <%= render 'form' %>
  </div>
</div>

<div id="feed">
    <%= render @posts %>
</div>

<div id="infinite-scrolling">
  <%= will_paginate @posts %>
</div>

blog/app/views/posts/new.html.erb
<h1 >New Post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path, class: "btn btn-primary btn-sm"  %>

blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
  <%= best_in_place @post, :title, :as => :input %>
</p>

<p>
  <b>Published at:</b>
  <%= @post.published_at %>
  <%= best_in_place @post, :published_at, :as => :date %>
</p>

<p>
  <b>Content:</b>
  <%= @post.body %>
  <%= best_in_place @post, :body, type: :cktext_area, :as => :cktext_area, :ok_button => 'Save', :cancel_button => 'Cancel'%>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path, class: "btn btn-primary btn-sm"  %>

  <%= render 'images/images' %>
  <%= render 'images/form' %>

blog/app/views/posts/update.js.erb
$("#edit_post_<%= @post.id %>").replaceWith("<%= j render 'posts/post', post: @post %>");

blog/app/views/shared/post_page.js.erb
$('#feed').append('<%= j render @posts %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

blog/app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger ">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      The form contains <%= pluralize(@user.errors.count, "error") %>.

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
  </div>
<% end %>

blog/app/views/users/_errors.html.erb
<div class='alert'>
  <ul>
    <% for message in @user.errors.full_messages %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

blog/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="container">
    <h1 class="text-center login-title">Update your profile</h1>
    <div class="row">

        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <div class="account-wall">
                <%= form_for @user do |f| %>
                <%= render 'error_messages' %>
                <div class="input-group">
                    <%= f.text_field :first_name, class: 'form-control', placeholder: 'First name' %>
                    <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last name' %>
                    <%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>
                    <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
                    <%= f.text_field :birthday, :class => 'datepicker' %>
                    <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
                    <!-- <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password Confirmation' %> -->
                </div>
                <br>
                <%= f.submit 'Save changes' , class: 'btn btn-lg btn-primary btn-block' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

blog/app/views/users/index.html.erb
<h1> All users </h1>
<% @users.each do |user|  %>
<p> <%= user.full_name %> </p>
<% end %>

blog/app/views/users/new.html.erb
<div class="container">
<h1 class="text-center login-title">Sign up!</h1>
<div class="row">

      <div class="col-sm-6 col-md-4 col-md-offset-4">
          <div class="account-wall">
            <%= form_for @user do |f| %>
              <%= render 'error_messages' %>
            <div class="input-group">
              <%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>
              <%=  f.text_field :email, class: 'form-control', placeholder: 'Email' %>
              <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
              <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password Confirmation' %>
            </div>
            <br>
            <%= f.submit 'Create user' , class: 'btn btn-lg btn-primary btn-block', remote: true %>
            <% end %>
          </div>
    </div>
</div>
</div>